[package]
name = "secretik"
version = "0.1.0"
edition = "2024"
readme = "README.md"
license = "MIT"
repository = "https://github.com/swfit1337/secretik"

[dependencies]
clap = { version = "4.5.34", features = ["derive"] }
names = "0.14.0"
