name: Release Binaries

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    env:
      BIN_NAME: secretik
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            name: linux-x86_64

          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            name: linux-aarch64

          - os: macos-latest
            target: x86_64-apple-darwin
            name: macos-x86_64

          - os: macos-latest
            target: aarch64-apple-darwin
            name: macos-aarch64

    name: Build ${{ matrix.name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Install dependencies (Linux ARM only)
        if: matrix.target == 'aarch64-unknown-linux-gnu'
        run: sudo apt-get update && sudo apt-get install -y gcc-aarch64-linux-gnu

      - name: Build release
        run: |
          cargo build --release --target=${{ matrix.target }}
          mkdir -p dist
          cp target/${{ matrix.target }}/release/${{ env.BIN_NAME }} dist/${{ env.BIN_NAME }}-${{ matrix.name }}

      - name: Upload release asset
        uses: softprops/action-gh-release@v2
        with:
          files: dist/${{ env.BIN_NAME }}-${{ matrix.name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
